Repository go-kratos/kratos-layout, pull requests merged in 2024-08, with the labels that each got.

#144 dep: upgrade wire to v0.6.0 #143
  Makefile
  cmd/server/wire_gen.go
  go.mod
  go.sum
Labels: size:S, lgtm

#148 fix(protobuf): upgrade protobuf version to avoid CVE-2024-24786
  go.mod
Labels: size:XS, lgtm

#150 bump kratos version
  go.mod
  go.sum
Labels: size:M

#149 fix:update the version of grpc
  go.mod
Labels: size:XS, lgtm

#151 fix go version in action
  .github/workflows/go.yml
  go.mod
  go.sum
Labels: size:M
